version: '3.9'
services:
  web:
    build:
      context: ..
    container_name: app
    image: app
#    image: wmgpznj4/web-ejb
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: 250M
        reservations:
#          cpus: '0.4'
          memory: 190M
    ports:
      - '80:80'
    expose:
      - '80'
    environment:
      JDBCDRIVER: 'com.mysql.cj.jdbc.Driver'
      JDBCPROVIDER: 'mysql'
      JDBCHOST: db
      JDBCPORT: '3306'
      SCHEMADB: 'web_ejb'
      JDBCUSER: 'admin_db'
      JDBCPASS: 'password'
      USESSL: 'false'
#      TZ: 'Europe/Kiev'
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - db

  db:
    container_name: db
#    image: mysql:8.0.25
#    image: mysql/mysql-server:8.0.25
    image: mariadb
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 130M
        reservations:
#          cpus: '0.25'
          memory: 100M
    restart: always
    ports:
    - '3307:3306'
    expose:
      - '3306'
    environment:
      MYSQL_DATABASE: 'web_ejb'
      MYSQL_USER: 'admin_db'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'PASSWORD'
      MYSQL_ROOT_HOST: '%'
      TZ: 'Europe/Kiev'
    volumes:
      - ../db:/tmp/database
#      - ../db:/docker-entrypoint-initdb.d
      - ../db/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  hello-world:
    container_name: hello-world
    image: hello-world
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 50M
#        reservations:
#          cpus: '0.05'
#          memory: 20M
    depends_on:
      web:
        condition: service_healthy
